### ISSUE TITLE
sudo - config  print lastrunfile output mismatch

### ISSUE THREAD

**Issue by digitalprecision** [aswen/nagios-plugins#24]
So, with sudo being used for commands, and having to add nagios user to sudoers per docs at top of script, I noticed the following behavior.

If I assume the nagios user:

```
$ -> sudo sudo -s -u nagios
bash-4.1$ /usr/bin/puppet --configprint lastrunfile
/var/spool/nagios/.puppet/var/state/last_run_summary.yaml
```
But then run the same command as su:

```
$ -> puppet --configprint lastrunfile
/var/lib/puppet/state/last_run_summary.yaml
```

The result when run via nagios and su do not match, which is why the parse_yaml function was hanging indefinitely. After hardcoding the path the parse_yaml function worked as expected.

Sidenote: You should be able to remove the sudo references in the script. If NRPE was compiled to run under nagios user or via nrpe_user in nrpe.cfg, and the script has 755 perms with and accessible as nagios then you shouldn't need to mess with sudoers etc.

**Comment by digitalprecision** [comment]
I assume this is why you added the ability to pass in last run file via arguments, so no fix necessary, just saying you could do away with sudo if perms are correct.

**Comment by aswen** [comment]
Your 1st assumption is wrong. The command executed by the nrpe daemon (running as user nagios) is: `sudo /usr/bin/puppet config print lastrunfile`. That yields the global puppet config. In your example you use sudo to become user nagios and then run the command `/usr/bin/puppet --configprint lastrunfile`. (in which case you'd have to alter the lines in your sudoers file btw. If you'r on a >=3 version of puppet you should use `puppet config print lastrunfile`.

I'll give you an example on one of our servers. First I run puppet as myself then as root:
```
server ~ # puppet config print lastrunfile
/home/alexander.swen/.puppet/var/state/last_run_summary.yaml
server ~ # sudo puppet config print lastrunfile
/var/lib/puppet/state/last_run_summary.yaml
```
So, now you see why check_puppet_agent has to run those config print commands as root. Otherwise the personal lastrunfile of user Nagios would be evaluated and I think that results in big bad errors ;-)
